version: 1.0.{build}
image:
  - Visual Studio 2017
  - Ubuntu2204

environment:
  CLICOLOR_FORCE: 1
  CHERE_INVOKING: 1 # Tell Bash to inherit the current working directory
  matrix:
    - MSYSTEM: MINGW64
    - MSYSTEM: LINUX

matrix:
  exclude:
    - image: Visual Studio 2017
      MSYSTEM: LINUX
    - image: Ubuntu2204
      MSYSTEM: MINGW64

for:
  -
    matrix:
      only:
        - MSYSTEM: MINGW64
    build_script:
      ps: "C:\\msys64\\usr\\bin\\bash -lc @\"\n
      pacman -S --quiet --noconfirm --needed re2c 2>&1\n
      ./configure.py --bootstrap --platform mingw 2>&1\n
      ./ninja all\n
      ./misc/ninja_syntax_test.py 2>&1\n\"@"
  - matrix:
      only:
        - image: Ubuntu2204
    build_script:
      - ./configure.py --bootstrap
      - ./ninja all
      - misc/ninja_syntax_test.py
      - misc/output_test.py

test: off
