version: 2.1

jobs:
  install:
    docker:
      - image: ubuntu:20.04
    steps:
      - checkout
      - run:
          name: Setup timezone and update packages
          command: |
            echo "America/New_York" > /etc/timezone
            ln -snf /usr/share/zoneinfo/America/New_York /etc/localtime
            apt-get update
            DEBIAN_FRONTEND=noninteractive apt-get install -y tzdata
      - run:
          name: Add LLVM repository
          command: |
            wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key|sudo apt-key add -
            echo "deb http://apt.llvm.org/focal/ llvm-toolchain-focal-14 main" | sudo tee /etc/apt/sources.list.d/llvm.list
            apt-get update
      - run:
          name: Install Clang and other tools
          command: |
            apt-get install -y clang-14
            apt-get install -y cmake
            apt-get install -y clang-tidy
            apt-get install -y clang-format

  format_tidy:
    docker:
      - image: ubuntu:20.04
    steps:
      - checkout
      - run:
          name: Run Clang-Format
          command: |
            find ./src -iname "*.cpp" -o -iname "*.h" | xargs clang-format -i
            git diff --exit-code
      - run:
          name: Run Clang-Tidy
          command: |
            find ./src -iname "*.cpp" | xargs clang-tidy -p .

workflows:
  version: 2
  build_and_test:
    jobs:
      - install
      - format_tidy:
          requires:
            - install
