version: 2.1

jobs:
  install_format_tidy:
    docker:
      - image: ubuntu:22.04
    steps:
      - checkout
      - run:
          name: Setup timezone and update packages
          command: |
            echo "America/New_York" > /etc/timezone
            ln -snf /usr/share/zoneinfo/America/New_York /etc/localtime
            apt-get update
            DEBIAN_FRONTEND=noninteractive apt-get install -y tzdata
      - run:
          name: Install Clang tools and create symlinks
          command: |
            apt-get update
            apt-get install -y clang-14 clang-format-14 clang-tidy-14
            update-alternatives --install /usr/bin/clang++ clang++ /usr/bin/clang++-14 100
            update-alternatives --install /usr/bin/clang clang /usr/bin/clang-14 100
            update-alternatives --install /usr/bin/clang-format clang-format /usr/bin/clang-format-14 100
            update-alternatives --install /usr/bin/clang-tidy clang-tidy /usr/bin/clang-tidy-14 100
      - run:
          name: Verify Clang tools installation
          command: |
            clang++ --version
            clang --version
            clang-format --version
            clang-tidy --version
      - run:
          name: install cmake and git
          command: apt-get install -y cmake git
      - run:
          name: Run Clang-Format
          command: |
            find . -iname "*.cpp" -o -iname "*.cc" -o -iname "*.h" | xargs clang-format -i
            git diff --exit-code
      - run:
          name: Run Clang-Tidy
          command: |
            find ./src -iname "*.cpp" -o -iname "*.cc" -o -iname "*.h" | xargs clang-tidy -p .
      - run:
          name: Building Unit test
          command: |
            mkdir build
            cd build
            cmake .. -DCMAKE_CXX_COMPILER=$(which clang++-14)
            cmake --build . --target cppcmake_unit_test
            ./cppcmake_unit_test



workflows:
  version: 2
  build_and_test:
    jobs:
      - install_format_tidy

