version: 2.1

jobs:
  install:
    docker:
      - image: ubuntu:20.04
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            echo 12 |apt-get update
            apt-get install -y clang-14
            apt-get install -y cmake
            apt-get install -y clang-tidy 
            apt-get install -y clang-format

  format_tidy:
    docker:
      - image: ubuntu:20.04
    steps:
      - checkout
      - run:
          name: Run Clang-Format
          command: |
            find ./src -iname "*.cpp" -o -iname "*.h" | xargs clang-format -i
            git diff --exit-code
      - run:
          name: Run Clang-Tidy
          command: |
            find ./src -iname "*.cpp" | xargs clang-tidy -p .

workflows:
  version: 2
  build_and_test:
    jobs:
      - install
      - format_tidy:
          requires:
            - install
